
.PHONY: all
all : hydrothermalVenture1 hydrothermalVenture2

hydrothermalVenture1 : hydrothermalVenture1.o
	gcc -g -o hydrothermalVenture1 hydrothermalVenture1.o

hydrothermalVenture2 : hydrothermalVenture2.o
	gcc -g -o hydrothermalVenture2 hydrothermalVenture2.o

hydrothermalVenture1.o :

hydrothermalVenture2.o :

clean :
	rm hydrothermalVenture1 hydrothermalVenture2 *.o
